### ISSUE TITLE
App crash on Task 7 Step 2. Unable to create call adapter for class java.lang.Strin

### ISSUE THREAD

**Issue by tigerlily777** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#158]
**URL of codelab:**

https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet#6
**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**
[7. Add Internet permission and Exception Handling](https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet#6)
Task 7 Step 2

**Describe the problem**
After I add internet permission in manifest and rebuild the app, I didn't see the json format text displaying on the screen, instead the app crashed.

**Steps to reproduce?**
1. Follow the steps until Task 7 Step 1
3. App crashes on launch

**Versions**
_Android Studio version:_ Android Studio Iguana 2023.2.1 Patch 2
_API version of the emulator:_ Api34

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
Logcat log:
FATAL EXCEPTION: main
                                                                                                    Process: com.example.marsphotos, PID: 31451
                                                                                                    java.lang.IllegalArgumentException: Unable to create call adapter for class java.lang.String
                                                                                                        for method MarsApiService.getPhotos
                                                                                                    	at retrofit2.Utils.methodError(Utils.java:54)
                                                                                                    	at retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:116)
                                                                                                    	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:67)
                                                                                                    	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
                                                                                                    	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
                                                                                                    	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy2.getPhotos(Unknown Source)
                                                                                                    	at com.example.marsphotos.ui.screens.MarsViewModel$getMarsPhotos$1.invokeSuspend(MarsViewModel.kt:45)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at com.example.marsphotos.ui.screens.MarsViewModel.getMarsPhotos(MarsViewModel.kt:44)
                                                                                                    	at com.example.marsphotos.ui.screens.MarsViewModel.<init>(MarsViewModel.kt:35)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.kt:202)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:324)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:306)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:280)
                                                                                                    	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                                                                    	at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:215)
                                                                                                    	at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:156)
                                                                                                    	at com.example.marsphotos.ui.ComposableSingletons$MarsPhotosAppKt$lambda-1$1$1.invoke(MarsPhotosApp.kt:82)
                                                                                                    	at com.example.marsphotos.ui.ComposableSingletons$MarsPhotosAppKt$lambda-1$1$1.invoke(MarsPhotosApp.kt:48)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:132)
                                                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:114)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:111)
                                                                                                    	at com.example.marsphotos.ui.ComposableSingletons$MarsPhotosAppKt$lambda-1$1.invoke(MarsPhotosApp.kt:46)
                                                                                                    	at com.example.marsphotos.ui.ComposableSingletons$MarsPhotosAppKt$lambda-1$1.invoke(MarsPhotosApp.kt:45)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)

**Comment by tigerlily777** [comment]
Just invalidated cache and restarted Android studio, run the build again, it works now.
