### ISSUE TITLE
Get Data from the Internet

### ISSUE THREAD

**Issue by gbygrave** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#163]
**URL of codelab:**
https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-5-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-getting-data-internet#7

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**
8

**Describe the problem**
Following the instructions in the step, upon attempting to run the application, it crashed with the following (root cause) exception:
`Caused by: kotlinx.serialization.SerializationException: Serializer for class 'MarsPhoto' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
at kotlinx.serialization.internal.PlatformKt.serializerNotRegistered(Platform.kt:31)
at kotlinx.serialization.SerializersKt__SerializersJvmKt.serializer(SerializersJvm.kt:77)
at kotlinx.serialization.SerializersKt.serializer(Unknown Source:1)
at kotlinx.serialization.SerializersKt__SerializersJvmKt.serializerByJavaTypeImpl$SerializersKt__SerializersJvmKt(SerializersJvm.kt:113)
at kotlinx.serialization.SerializersKt__SerializersJvmKt.serializer(SerializersJvm.kt:76)
at kotlinx.serialization.SerializersKt.serializer(Unknown Source:1)
at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer.serializer(Serializer.kt:21)
at com.jakewharton.retrofit2.converter.kotlinx.serialization.Factory.responseBodyConverter(Factory.kt:26)
at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:362)
at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:345)
at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:124)
... 240 more`

**Steps to reproduce?**
Not applicable.

**Versions**
_Android Studio version:_
2023.2.1 Patch 2
_API version of the emulator:_
33

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
Really not sure if this is me or just some weird combination of versions or something else - I'm sure it worked for you when you wrote the course.  I did some searching and wiggled around this issue by including the plugin at the project level, as well as the (as per your instruction) module level.  HTH.  (Apologies if this ends up wasting your time.)
![image](https://github.com/user-attachments/assets/269b552f-098a-4470-aa50-70334ecc796f)

**Comment by gbygrave** [comment]
Hey, closing this as the issue has gone away with some lib upgrades.  I think specifically this stopped happening when I upgraded to 1.9.10 of org.jetbrains.kotlin.plugin.serialization.  Sorry for the bum steer.
