### ISSUE TITLE
Get Data from the Internet

### ISSUE THREAD

**Issue by georgejas** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#181]
**URL of codelab:**

https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet#7

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**

step 7 [Parse the JSON response with kotlinx.serialization](https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet#7)

**Describe the problem**

id("org.jetbrains.kotlin.plugin.serialization") version "1.8.10"
needs to be 
id("org.jetbrains.kotlin.plugin.serialization") version "1.9.10"

or the app will crash with this stack:

FATAL EXCEPTION: main
                                                                                                    Process: com.example.marsphotos, PID: 14182
                                                                                                    java.lang.IllegalArgumentException: Unable to create converter for java.util.List<com.example.marsphotos.network.MarsPhoto>
                                                                                                        for method MarsApiService.getPhotos
                                                                                                    	at retrofit2.Utils.methodError(Utils.java:54)
                                                                                                    	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:126)
                                                                                                    	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:85)
                                                                                                    	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
                                                                                                    	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
                                                                                                    	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy2.getPhotos(Unknown Source)
                                                                                                    	at com.example.marsphotos.ui.screens.MarsViewModel$getMarsPhotos$1.invokeSuspend(MarsViewModel.kt:53)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at com.example.marsphotos.ui.screens.MarsViewModel.getMarsPhotos(MarsViewModel.kt:51)
                                                                                                    	at com.example.marsphotos.ui.screens.MarsViewModel.<init>(MarsViewModel.kt:42)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.kt:202)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:324)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:306)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:280)
                                                                                                    	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                                                                    	at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:215)
                                                                                                    	at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:156)
                                                                                                    	at com.example.marsphotos.ui.ComposableSingletons$MarsPhotosAppKt$lambda-1$1$1.invoke(MarsPhotosApp.kt:82)
                                                                                                    	at com.example.marsphotos.ui.ComposableSingletons$MarsPhotosAppKt$lambda-1$1$1.invoke(MarsPhotosApp.kt:48)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:132)
                                                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:114)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:111)
                                                                                                    	at com.example.marsphotos.ui.ComposableSingletons$MarsPhotosAppKt$lambda-1$1.invoke(MarsPhotosApp.kt:46)
                                                                                                    	at com.example.marsphotos.ui.ComposableSingletons$MarsPhotosAppKt$lambda-1$1.invoke(MarsPhotosApp.kt:45)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)

**Steps to reproduce?**
1. Complete codelab through step 7
2. Run the app
3. EXPECTED: App displays "Success: 838 Mars photos retrieved"
4. ACTUAL: Crashes with above stack

**Versions**
_Android Studio version:_  Ladybug
_API version of the emulator:_. 35

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

The solution code here has the right version (1.9.10), so I suspect this was known, and the codelab text just not updated. 
https://github.com/google-developer-training/basic-android-kotlin-compose-training-mars-photos/blob/repo-starter/app/build.gradle.kts

**Comment by georgejas** [comment]
Sorry, this is for step 8 (not step 7).
